const actionTypes = {
    SEARCHWORD: "SEARCHWORD",
    MENU_REQUESTED: "MENU_REQUESTED",
    MENU_RECEIVED: "MENU_RECEIVED",
    MENU_FAILED: "MENU_FAILED",
    RATING_REQUESTED: "RATING_REQUESTED",
    RATING_RECEIVED: "RATING_RECEIVED",
    RATING_FAILED: "RATING_FAILED",
    PAGINATION: "PAGINATION"
}

export default actionTypes