const actionTypes = {
    SEARCHWORD: "SEARCHWORD",
    MENU_REQUESTED: "MENU_REQUESTED",
    MENU_RECEIVED: "MENU_RECEIVED",
    MENU_FAILED: "MENU_FAILED",
    RATING_REQUESTED: "RATING_REQUESTED",
    RATING_RECEIVED: "RATING_RECEIVED",
    RATING_FAILED: "RATING_FAILED",
    PAGINATION: "PAGINATION",
    SAVE_FAVOURITE_REQUESTED: "SAVE_FAVOURITE_REQUESTED",
    SAVE_FAVOURITE_RECIEVED: "SAVE_FAVOURITE_RECIEVED",
    SAVE_FAVOURITE_FAILED: "SAVE_FAVOURITE_FAILED",
    SHOW_FAVOURITE_REQUESTED: "SHOW_FAVOURITE_REQUESTED",
    SHOW_FAVOURITE_RECIEVED: "SHOW_FAVOURITE_RECIEVED",
    SHOW_FAVOURITE_FAILED: "SHOW_FAVOURITE_FAILED",
}

export default actionTypes